pipeline:
  delegateSelectors:
  - gcp-delegate
  identifier: demo
  name: demo
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
  - stage:
      description: ''
      identifier: CI_stage
      name: CI_stage
      spec:
        cloneCodebase: false
        execution:
          steps:
          - step:
              identifier: GitClone1
              name: GitClone-1
              spec:
                build:
                  spec:
                    branch: main
                  type: branch
                connectorRef: gitconnect
                repoName: helwrld
              type: GitClone
          - step:
              identifier: Run2
              name: Run-2
              spec:
                command: |-
                  cd helwrld
                  javac helwrld.java
                  jar cvf myHelloWorld.jar *.class
                  ls
                shell: Bash
              type: Run
          - step:
              identifier: SaveCacheGCS3
              name: SaveCacheGCS-3
              spec:
                archiveFormat: Tar
                bucket: apprepository
                connectorRef: demo
                key: java
                sourcePaths:
                - helwrld/myHelloWorld.jar
              type: SaveCacheGCS
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      tags: {}
      type: CI
  - stage:
      description: ''
      identifier: Custom_stage
      name: Custom_stage
      spec:
        execution:
          steps:
          - step:
              identifier: Email4
              name: Email-4
              spec:
                body: This is a test mail
                cc: ''
                subject: Testing email notification
                to: arjunprasaatha@virtusa.com
              timeout: 1d
              type: Email
      tags: {}
      type: Custom
  tags: {}
